services:
  sentinel-db:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: checker
      MYSQL_PASSWORD: sentinel
      MYSQL_ROOT_PASSWORD: sentinelroot
      MYSQL_USER: user
      TZ: Europe/Rome
    image: mariadb:10.3
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 100m
    ports:
    - published: 3311
      target: 3306
    restart: unless-stopped
    volumes:
    - ./database:/database:rw
    - ./dump.sql:/docker-entrypoint-initdb.d/0_init.sql:rw
    - ./mariadb-conf:/etc/mysql/mariadb.conf.d:rw
    - sentinel-db:/var/lib/mysql:rw
  sentinel:
    container_name: sentinel
    environment:
    - DOCKER_HOST=tcp://docker-socket-proxy:2375
    image: fabriziomereu/sentinel:v0.5.86
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 100m
    command: ["sleep", "3600"]
    ports:
    - published: 9080
      target: 9080
    restart: unless-stopped
    volumes:
    - ./confs:/confs:rw
    - ./users.txt:/app/users.txt:rw
    - sentinel:/app/data
    - ./conf.json:/app/conf.json:rw
    - sentinel-keys:/ssh_keys
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_socket_proxy
    environment:
      - CONTAINERS=1      # Allow listing/running containers
      - IMAGES=1          # Allow image inspection/pulling
      - INFO=1            # Allow basic system info
      - NETWORKS=0        # Disallow network changes
      - VOLUMES=0         # Disallow volume changes
      - BUILD=0           # Disallow docker build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"
volumes:
  sentinel: {}
  sentinel-db: {}
  sentinel-keys: {}